version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgres-local
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
  activemq:
    container_name: activemq-local
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./data/activemq/data:/data/activemq
      - ./data/activemq/log:/var/log/activemq
  app:
    container_name: spring-api
    build: .
    env_file: .env
    links:
      - postgresql
    environment:
      DB_HOST: postgresql
      DB_PASS: postgres
      DB_NAME: database
      MQ_HOST: activemq
    ports:
      - 8080:8080
    depends_on:
      - activemq
      - postgresql